apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: school-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Ahmedlebshten/School_Management_System_CD.git
    targetRevision: master
    path: school

  destination:
    server: https://kubernetes.default.svc
    namespace: school

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
