apiVersion: apps/v1
kind: Deployment
metadata:
  name: school-management-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: school_management_system
  template:
    metadata:
      labels:
        app: school_management_system
    spec:
      containers:
      - name: school-management-system
        image: ahmedlebshten/school_management_system:4
        ports:
        - containerPort: 80
