apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: school
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3-mysql
  resources:
    requests:
      storage: 5Gi