apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: school
  name: school-management-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: school-management-system
  template:
    metadata:
      labels:
        app: school-management-system
    spec:

# waiting for mysql container is ready
      initContainers:
        - name: wait-for-mysql
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z mysql 3306; do
                echo "Waiting for MySQL..."
                sleep 3
              done
      
      containers:
        - name: school-management-system
        - image: 731628759499.dkr.ecr.us-east-1.amazonaws.com/school-management-system:24
          ports:
            - containerPort: 80

# connection between the school wep app and mysql database 
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_HOST

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_DATABASE

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER

            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD

            - name: DB_PORT
              value: "3306"

          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
