apiVersion: v1
kind: Secret
metadata:
  name: school-env
  namespace: school
type: Opaque
stringData:
  DB_HOST: db
  DB_NAME: school
  DB_USER: root
  DB_PASS: password
  DB_CHARSET: utf8mb4

  MAIL_DRIVER: smtp
  MAIL_FROM_ADDRESS: no-reply@school.local
  CONTACT_EMAIL: ahmedlebshtenlebshten@gmail.com

  SMTP_HOST: sandbox.smtp.mailtrap.io
  SMTP_PORT: "2525"
  SMTP_USERNAME: d375cca0275be7
  SMTP_PASSWORD: e314ef7d2b77a8
  SMTP_ENCRYPTION: tls
